// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v7.35.1
// source: agent/v1/agent.proto

// ProbeOne Agent 通信契约
//
// 设计红线（修改本文件前务必阅读 PRD 7.1）：
//   Agent 是只读的。服务端只能接收数据，不能向 Agent 下发任何命令。
//   因此本文件中不存在 Exec / RunCommand / Terminal / FileManager / Upgrade
//   等任何具有执行能力的 RPC 方法。唯一的服务端→客户端消息是 ConfigSync，
//   它只携带采集配置（采样间隔、启用的指标项、时区），不产生副作用。
//
//   这是本项目与 nezhahq/nezha 的根本区别。哪吒的 Command / Terminal /
//   FileManager 三个任务类型被安全厂商披露为 RAT 滥用载体，攻击者可用其
//   获得 root / SYSTEM shell，且该二进制在 72 家杀毒厂商处零检出。
//   详见 PRD 1.1。

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AgentService_Handshake_FullMethodName    = "/probeone.agent.v1.AgentService/Handshake"
	AgentService_ReportStream_FullMethodName = "/probeone.agent.v1.AgentService/ReportStream"
	AgentService_ReportOnce_FullMethodName   = "/probeone.agent.v1.AgentService/ReportOnce"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// 一次��鉴权。客户端凭据通过 gRPC metadata 传递：
	//
	//	client-uuid: 节点 UUID
	//	client-secret: 节点密钥明文
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// 双向流：Agent 持续推送指标，Server 仅返回 ACK。
	// 流不可用时降级为 ReportOnce。
	ReportStream(ctx context.Context, opts ...grpc.CallOption) (AgentService_ReportStreamClient, error)
	// 降级路径：无流能力时使用，每次上报一次。
	ReportOnce(ctx context.Context, in *AgentMessage, opts ...grpc.CallOption) (*ServerMessage, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, AgentService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportStream(ctx context.Context, opts ...grpc.CallOption) (AgentService_ReportStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ReportStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceReportStreamClient{ClientStream: stream}
	return x, nil
}

type AgentService_ReportStreamClient interface {
	Send(*AgentMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type agentServiceReportStreamClient struct {
	grpc.ClientStream
}

func (x *agentServiceReportStreamClient) Send(m *AgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceReportStreamClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) ReportOnce(ctx context.Context, in *AgentMessage, opts ...grpc.CallOption) (*ServerMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerMessage)
	err := c.cc.Invoke(ctx, AgentService_ReportOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// 一次��鉴权。客户端凭据通过 gRPC metadata 传递：
	//
	//	client-uuid: 节点 UUID
	//	client-secret: 节点密钥明文
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// 双向流：Agent 持续推送指标，Server 仅返回 ACK。
	// 流不可用时降级为 ReportOnce。
	ReportStream(AgentService_ReportStreamServer) error
	// 降级路径：无流能力时使用，每次上报一次。
	ReportOnce(context.Context, *AgentMessage) (*ServerMessage, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedAgentServiceServer) ReportStream(AgentService_ReportStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportStream not implemented")
}
func (UnimplementedAgentServiceServer) ReportOnce(context.Context, *AgentMessage) (*ServerMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportOnce not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportStream(&agentServiceReportStreamServer{ServerStream: stream})
}

type AgentService_ReportStreamServer interface {
	Send(*ServerMessage) error
	Recv() (*AgentMessage, error)
	grpc.ServerStream
}

type agentServiceReportStreamServer struct {
	grpc.ServerStream
}

func (x *agentServiceReportStreamServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceReportStreamServer) Recv() (*AgentMessage, error) {
	m := new(AgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AgentService_ReportOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportOnce(ctx, req.(*AgentMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "probeone.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _AgentService_Handshake_Handler,
		},
		{
			MethodName: "ReportOnce",
			Handler:    _AgentService_ReportOnce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportStream",
			Handler:       _AgentService_ReportStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
